name: Build and upload Debian/Ubuntu SELinux module packages

on: 
  workflow_call:
    inputs:
      source_repo_location:
        description: 'Provides the directory where the source repository is to be checked out'
        required: false
        default: 'SOURCE_REPO'
        type: string
      build_material_dir:
        description: 'Provides the relative path (in the source repository) where the Makefile and the control, changelog and copyright files are located.'
        required: false
        default: 'dpkg'
        type: string
      build_distro:
        description: 'Distribution family'
        required: true
        type: string
      build_distro_versions:
        description: 'Matrix of distribution versions to build for'
        required: true
        default: '[ "11", "12" ]'
        type: string
      release_upload_url:
        description: 'Provides the URL to upload the packages to'
        required: false
        default: ''
        type: string
      package_version:
        description: 'Package version'
        required: true
        type: string
      previous_tag:
        description: 'Previous tag used to build changelog file'
        required: false
        type: string
        default: ''
      output_dir:
        description: 'Directory name where packages are generated.'
        required: false
        default: artifacts
        type: string
      sftp_server:
        description: Name or IP address of SFTP server to upload RPMs to
        required: false
        type: string
      sftp_user:
        description: User for SFTP upload of RPMs
        required: false
        type: string
      sftp_remote_path:
        description: Remote path to upload RPMs to
        required: false
        type: string
    secrets:
      gpg_private_key:
        description: The GPG private key
        required: true
      gpg_private_key_password:
        description: The GPG private key password
        required: true
      sftp_password:
        description: SSH password for SCP/SFTP uploads
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create SELinux module from sources

    strategy:
      matrix: 
        distro_version: ${{ fromJSON(inputs.build_distro_versions) }}
      
    env:
      gpg_private_key_file: private_key.gpg
      gpg_private_key: ${{ secrets.gpg_private_key }}
      gpg_private_key_password: ${{ secrets.gpg_private_key_password }}
      pkgs_dir: ${{github.workspace}}/build/${{ inputs.output_dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          path: ${{github.workspace}}/${{ inputs.source_repo_location }}
        
      - name: Prepare build workspace and create private key file from secret.
        shell: bash
        run: |
          mkdir -m 0755 -p ${{github.workspace}}/build/${{ inputs.output_dir }}
          echo "${gpg_private_key}" | base64 -di > ${{github.workspace}}/build/${gpg_private_key_file}
          echo "${gpg_private_key_password}" > ${{github.workspace}}/build/.${gpg_private_key_file}.passphrase
          ls -l ${{github.workspace}}/build/${gpg_private_key_file} ${{github.workspace}}/build/.${gpg_private_key_file}.passphrase

      - name: Call Docker DEB build
        id: dockerbuild
        uses: lhqg/action-os-debbuild-selinux@main
        with:
          distro: ${{ inputs.build_distro }}
          distro_version: ${{ matrix.distro_version }}
          source_repo_location: ${{ inputs.source_repo_location }}
          build_material_dir: ${{ inputs.build_material_dir }}
          package_version: ${{ inputs.package_version }}
          output_dir: ${{ inputs.output_dir }}
          gpg_key_name: ${{ vars.DEB_SIGNING_KEY_NAME }}
          gpg_key_id: ${{ vars.DEB_SIGNING_KEY_ID }}
          gpg_private_key_file: ${{ env.gpg_private_key_file }}

      - name: SFTP Upload pkgs
        if: ${{ inputs.sftp_server != '' && inputs.sftp_remote_path != '' && inputs.sftp_user != '' }}
        id: sftp_upload_debs
        uses: lhqg/EXT-sftp-upload-action@latest
        with:
            server: ${{ inputs.sftp_server }}
            username: ${{ inputs.sftp_user }}
            password: ${{ secrets.sftp_password }}
            uploads: |
              ${{github.workspace}}/build/${{ inputs.output_dir }}/${{ inputs.build_distro }}/ => ${{ inputs.sftp_remote_path }}/

      - name: HTTP Upload packages
        if: ${{ startsWith(inputs.release_upload_url, 'https://') }}
        id: http_upload_pkgs
        shell: bash
        run: |

          grep -q '^https://' <<< '${{ inputs.release_upload_url }}'
          rc_grep=$?

          if [ -n "${pkgs_dir}" -a -d "${pkgs_dir}" -a $rc_grep -eq 0 ]
          then
            echo "::notice title={title}::Searching ${pkgs_dir} for packages to upload"

            UPLOAD_URL=$( sed -e 's/{?name,label}/?name/' <<< '${{ inputs.release_upload_url }}' )
            echo "::notice title={title}::Uploading to ${UPLOAD_URL}"

            ls -lR ${pkgs_dir}

            cd ${pkgs_dir}

            rc=0
            count=0

            for pkg in $( find ${pkgs_dir} -type f -name '*.tar.bz2' )
            do 
              pkg_file_name=$(basename ${pkg})

              # Upload pkg
              echo "::debug title={debug}::Uploading ${pkg_file_name}:"
              curl \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/octet-stream" \
                -T ${pkg} \
                ${UPLOAD_URL}=${pkg_file_name}
              rc_curl=$?
              echo "::debug title={debug}::Upload return code: ${rc_curl}"
              [ $rc_curl -eq 0 ] && count=$(( $count + 1 )) || rc=1
            done
            echo "::notice title={title}::Total pkgs uploaded: ${count}."
            [ $count -lt 1 ] && rc=1
          else
            echo "::error title={title}:: Fatal: the signed packages directory is not set or does not exist."
            rc=1
          fi
          exit $rc
